---
name: Documentation Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/docs-lint.yaml'
      - 'docs/**'

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: .go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make docs-lint

  save-artifacts-on-fail:
    if: ${{ needs.docs-lint.result }} == 'failure'
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    if: ${{ needs.depscheck.result }} == 'failure'
    uses: ./.github/workflows/comment-failure.yaml
