---
name: Documentation Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'docs/**'
      - '.github/workflows/**'

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make docs-lint
